spring.main.banner-mode=CONSOLE
spring.web.error.whitelabel.enabled=true

spring.mvc.apiversion.enabled=true
spring.mvc.apiversion.use.path-segment=0

my.name=victor
my.location=france

filestorage.tmp-directory=\${java.io.tmpdir}